config/routes.rb
Rails.application.routes.draw do
  root 'people#index'
  
  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  
  validates :age, numericality: true
  validates :name, :age, :gender, presence: true
  
  def basic_info
    "#{self.name}, #{self.age}, #{self.gender}"
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end
  
  def create
    @person = Person.new(people_params)
 
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end
  
  def update
    @person = Person.find(params[:id])
  
    if @person.update(person_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end
  
  private
 
    def people_params
      params.require(:person).permit(:name, :age, :alive)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'People List', people_path %>
<%= link_to 'New Person', new_person_path %>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<%= form_for @person do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :age %>
  <%= f.text_field :age %>
  <br />

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
  <br />
 
  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
  <br />

  <%= f.label :gender %>
  <%= f.text_field :gender %>
  <br />

  <h6>Needs to be true or false</h6>
  <%= f.label :alive %>
  <%= f.text_field :alive %>
  <br />

  <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1> People </h1>
<h1> Pages </h1>
<p><%= link_to 'New Person Info', new_person_path %></p>
<% @people.each do |person| %>
  <h2><%= person.name %></h2>
  <%= link_to 'Info About Person', person %>
  <%= link_to 'Edit Person Info', edit_person_path(person) %>
  <%= link_to 'Destroy Page', person, method: :delete %>

<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>
<%= form_for @person do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :age %>
  <%= f.text_field :age %>
  <br />

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
  <br />
 
  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
  <br />

  <%= f.label :gender %>
  <%= f.text_field :gender %>
  <br />

  <h6>Needs to be true or false</h6>
  <%= f.label :alive %>
  <%= f.text_field :alive %>
  <br />

  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<h2><%= @person.age %></h2>
<h2><%= @person.hair_color %></h2>
<h2><%= @person.eye_color %></h2>
<h2><%= @person.gender %></h2>
<h2><%= @person.alive %></h2>

<%= link_to "Go Back", people_path %>